### PR TITLE
List Screen, Add Screen, Edit Screen

### PR DESCRIPTION
**Pull request by AnuraagBasu**
This PR contains the following screens for the app:
<li><b>List Screen</b><br/>
lists all the team members
</li>
<li><b>Add Screen</b><br/>
add a team member along with the basic info - name, email, phone, role
</li>
<li><b>Edit Screen</b><br/>
edit an existing team member's info or delete a team member altogether
</li>

### CODE REVIEW

**Comment by lalitpatel** [comment]
Hi @AnuraagBasu  
Thanks for getting back with the code. We will review this and get back to you asap. 👍

**Comment by adamstep** [comment]
Hi @AnuraagBasu ,
I noticed two issues with the project:
- When I created multiple users and then delete a user, all users disappear from the list. Only the one user should be deleted.
- When I add 1 user, the main screen says "You have 1 team members", which is not grammatically correct.

**Comment by AnuraagBasu** [comment]
Hi @adamstep,
Thank you for the feedback. I have made the required changes now.

**Comment by adamstep** [comment]
Thanks, these changes work well!

**Pull request merged**
